// Do not edit. This file is machine generated by the Resource DLL Wizard.

library PuttyCtnr;

{ITE} {DFMFileType} {Form\AboutForm.dfm}
{ITE} {DFMFileType} {Form\ChildForm.dfm}
{ITE} {DFMFileType} {Form\ConnectionForm.dfm}
{ITE} {DFMFileType} {Form\MainForm.dfm}
{ITE} {DFMFileType} {Form\MingwForm.dfm}
{ITE} {DFMFileType} {Form\PasswordForm.dfm}
{ITE} {DFMFileType} {Form\SyncKeyForm.dfm}
{ITE} {RCFileType} {PuttyCtnr_DRC.rc}

{$R 'Form\AboutForm.dfm' 'FormAbout:TForm'}
{$R 'Form\ChildForm.dfm' 'FormChild:TForm'}
{$R 'Form\ConnectionForm.dfm' 'FormConnection:TForm'}
{$R 'Form\MainForm.dfm' 'FormPuttyMain:TForm'}
{$R 'Form\MingwForm.dfm' 'FormMingw:TForm'}
{$R 'Form\PasswordForm.dfm' 'FormPassword:TForm'}
{$R 'Form\SyncKeyForm.dfm' 'FormSyncKey:TForm'}
{$R 'PuttyCtnr_DRC.res' 'PuttyCtnr_DRC.rc'}

{$E KOR}

begin
end.
